### PR TITLE
Fix app->lib->app calls

### PR DESCRIPTION
**Pull request by markburns**
Starting work on fixing - #14 , see there for more background

### CODE REVIEW

**Comment by muzfuz** [comment]
Great, I'll have another go at this tomorrow morning.

**Comment by muzfuz** [comment]
Amazing stuff.

**Comment by markburns** [comment]
Wait, that was accidental. This isn't fixed. I just merged some refactor stuff locally that I'd also pushed on this branch. The pre-factor stuff *is* in master. But not done any work on this issue itself

**Comment by muzfuz** [comment]
Ah no! No probs I'll take a look soon as I'm in this morning.

**Pull request merged**
