### PR TITLE
Sort glob results

### PR DESCRIPTION
**Pull request by paolobrasolin**
This solves #37

### CODE REVIEW

**Comment by markburns** [comment]
Hey awesome. Thanks for the contribution, actually the fix I’d like to see is to do the sort in the tests. 
If I remember correctly, I don’t think the sort order is relevant to the implementation.
If you can change it to that I’ll merge it in.

**Comment by paolobrasolin** [comment]
I think that sorting just in the tests might not cut it.

Here are the detail of one of the failures from #36:
```
  1) Delfos::FileSystem::DistanceCalculation#traversals should contain exactly "/tree/some_file", "/tree/even_more", and "/tree/another_top_level_file"
     Failure/Error: expect(a).to match_array(b.map { |f| t(f) }.map(&format))

       expected collection contained:  ["/tree/another_top_level_file", "/tree/even_more", "/tree/some_file"]
       actual collection contained:    ["/tree/another_top_level_file", "/tree/some_file"]
       the missing elements were:      ["/tree/even_more"]
     # ./spec/support/helper_methods.rb:30:in `match_file_array'
     # ./lib/delfos/file_system/distance_calculation_spec.rb:49:in `block (3 levels) in <module:FileSystem>'
```

Alphabetical sorting is assumed in the traversal algorithm, in that file/directory arrays are sliced by index to simulate _a human browsing a tree view_ to find the shortest path between two entries.

If the order changes then the traversed elements change too, and _the distance metrics change too_.

I think that's what the tests are catching here with the missing/additional elements.
Am I reading too much into this?

**Comment by markburns** [comment]
OK this is great. I was away from a machine when I replied.
I'm up to speed now and my intuition was wrong. You're absolutely correct.
And yes the tests caught this. 

Just for the record, I'm not sure what happened to the CI check, but I've run the tests locally and they pass.

Thanks for your help and I hope you enjoy using Delfos.

**Comment by markburns** [comment]
Fixes #37

**Pull request merged**
